# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160804_1524'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionsubscriber',
            unique_together=set([]),
        ),
    ]
