# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_collectionarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='code',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
